import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, ShieldCheck, X } from "lucide-react";
import { useNavigate, useSearchParams } from "react-router-dom";

import VerificationTabs, {
  type VerificationType,
} from "../../components/verification/VerificationTabs";

import TextVerifier from "../../components/verification/TextVerifier";
import FileUploader from "../../components/verification/FileUploader";
import AnalysisProgress from "../../components/verification/AnalysisProgress";
import VerificationInfo from "../../components/verification/VerificationInfo";

import "./Verify.css";

const API_URL = "http://localhost:5001";

export default function VerifyPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const [type, setType] =
    useState<VerificationType>("text");

  const [text, setText] = useState("");
  const [source, setSource] = useState("");
  const [file, setFile] = useState<File | null>(null);

  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  /*
   * Read verification type from URL.
   *
   * Example:
   * /verify?type=text
   * /verify?type=image
   * /verify?type=video
   * /verify?type=document
   */
  useEffect(() => {
    const queryType =
      searchParams.get("type") as VerificationType | null;

    if (
      queryType &&
      ["text", "image", "video", "document"].includes(queryType)
    ) {
      setType(queryType);
    }
  }, [searchParams]);

  /*
   * Change verification type.
   */
  const handleTypeChange = (
    nextType: VerificationType
  ) => {
    setType(nextType);

    setFile(null);
    setError("");
  };

  /*
   * Submit verification.
   */
  const handleSubmit = async () => {
    setError("");

    /*
     * TEXT VALIDATION
     */
    if (type === "text" && !text.trim()) {
      setError(
        "Enter content before starting the analysis."
      );
      return;
    }

    /*
     * FILE VALIDATION
     */
    if (type !== "text" && !file) {
      setError(
        `Select a ${type} before starting the analysis.`
      );
      return;
    }

    /*
     * Currently our backend is connected for TEXT
     * verification only.
     */
    if (type !== "text") {
      setError(
        `${type.charAt(0).toUpperCase() + type.slice(1)} verification is coming soon.`
      );
      return;
    }

    setLoading(true);

    try {
      /*
       * Send text verification to backend.
       */
      const response = await fetch(
        `${API_URL}/api/verifications`,
        {
          method: "POST",

          headers: {
            "Content-Type": "application/json",
          },

          body: JSON.stringify({
            type: "text",
            content: text.trim(),

            /*
             * Send source as well.
             *
             * Your backend can ignore this for now
             * if it doesn't use it yet.
             */
            source: source.trim(),
          }),
        }
      );

      /*
       * Try to parse backend response.
       */
      const data = await response.json();

      /*
       * Backend returned an error.
       */
      if (!response.ok || !data.success) {
        throw new Error(
          data.message ||
            "Verification failed. Please try again."
        );
      }

      /*
       * Make sure backend returned verification data.
       */
      if (!data.verification) {
        throw new Error(
          "Verification was created but no result was returned."
        );
      }

      /*
       * Get the verification ID generated by MongoDB/backend.
       */
      const verificationId =
        data.verification.verificationId;

      if (!verificationId) {
        throw new Error(
          "Verification ID was not returned by the server."
        );
      }

      /*
       * Navigate to:
       *
       * /result/TL-2026-XXXX
       *
       * ResultPage will use this ID to fetch
       * the actual verification.
       */
      navigate(`/result/${verificationId}`);

    } catch (err) {
      console.error(
        "Verification error:",
        err
      );

      setError(
        err instanceof Error
          ? err.message
          : "Something went wrong while analyzing the content."
      );

      setLoading(false);
    }
  };

  return (
    <div className="verify-shell">

      {/* =========================
          HEADER
      ========================== */}

      <header className="verify-nav">

        <div className="verify-nav-inner">

          {/* Brand */}
          <a
            href="/"
            className="verify-brand"
          >
            <span className="verify-mark">
              <span />
            </span>

            TruthLens
          </a>

          {/* Navigation */}
          <nav className="verify-links">

            <a href="/#how-it-works">
              How It Works
            </a>

            <a href="/#capabilities">
              Capabilities
            </a>

            <a href="/#evidence">
              Evidence
            </a>

            <a href="/#about">
              About
            </a>

          </nav>

          {/* Actions */}
          <div className="verify-nav-actions">

            <a href="/dashboard">
              Dashboard
            </a>

            <a
              href="/verify"
              className="verify-nav-cta"
            >
              Verify Content
            </a>

          </div>

        </div>

      </header>


      {/* =========================
          MAIN
      ========================== */}

      <main className="verify-main">

        {/* Page heading */}
        <motion.div
          className="verify-heading"
          initial={{
            opacity: 0,
            y: 8,
          }}
          animate={{
            opacity: 1,
            y: 0,
          }}
          transition={{
            duration: 0.4,
          }}
        >

          <span className="verify-eyebrow">
            TRUST & EVIDENCE VERIFICATION
          </span>

          <h1>
            Verify Digital Content
          </h1>

          <p>
            Analyze claims, images, videos, and
            documents using multiple evidence signals
            to assess their credibility and authenticity.
          </p>

        </motion.div>


        {/* =========================
            VERIFICATION WORKSPACE
        ========================== */}

        <section
          className="verify-workspace"
          aria-label="Verification workspace"
        >

          {/* Verification tabs */}
          <VerificationTabs
            selected={type}
            onChange={handleTypeChange}
          />


          <AnimatePresence mode="wait">

            {/* =====================
                ANALYSIS LOADING
            ====================== */}

            {loading ? (

              <AnalysisProgress
                key="progress"
                type={
                  type.charAt(0).toUpperCase() +
                  type.slice(1)
                }
              />

            ) : (

              <motion.div
                key={type}
                className="input-panel"
                initial={{
                  opacity: 0,
                  y: 8,
                }}
                animate={{
                  opacity: 1,
                  y: 0,
                }}
                exit={{
                  opacity: 0,
                  y: -8,
                }}
                transition={{
                  duration: 0.2,
                }}
              >

                {/* =====================
                    TEXT VERIFICATION
                ====================== */}

                {type === "text" ? (

                  <TextVerifier
                    text={text}
                    source={source}
                    onTextChange={setText}
                    onSourceChange={setSource}
                  />

                ) : (

                  /* =====================
                     FILE VERIFICATION
                  ====================== */

                  <div className="file-area">

                    {file ? (

                      <div className="file-selected">

                        <div className="file-symbol">
                          <ShieldCheck size={22} />
                        </div>

                        <div>
                          <strong>
                            {file.name}
                          </strong>

                          <small>
                            {file.type ||
                              "Uploaded file"}

                            {" · "}

                            {(
                              file.size /
                              1024 /
                              1024
                            ).toFixed(2)}

                            {" MB"}
                          </small>
                        </div>

                        <button
                          type="button"
                          onClick={() =>
                            setFile(null)
                          }
                          aria-label="Remove file"
                        >
                          <X size={17} />
                        </button>

                      </div>

                    ) : (

                      <FileUploader
                        type={type}
                        file={file}
                        onFileChange={setFile}
                      />

                    )}

                  </div>

                )}


                {/* =====================
                    ERROR
                ====================== */}

                {error && (

                  <p
                    className="verify-error"
                    role="alert"
                  >
                    {error}
                  </p>

                )}


                {/* =====================
                    ANALYZE BUTTON
                ====================== */}

                <button
                  type="button"
                  className="analyze-button"
                  disabled={
                    type === "text"
                      ? !text.trim()
                      : !file
                  }
                  onClick={handleSubmit}
                >

                  Analyze{" "}

                  {type.charAt(0).toUpperCase() +
                    type.slice(1)}

                  <ArrowRight size={16} />

                </button>

              </motion.div>

            )}

          </AnimatePresence>

        </section>


        {/* =========================
            INFORMATION
        ========================== */}

        <VerificationInfo />

      </main>

    </div>
  );
}